### PR TITLE
Tdbastar dynoplan

### PR DESCRIPTION
**Pull request by akmaralAW**

### CODE REVIEW

**Comment by akmaralAW** [comment]
current tdbA* for dynoplan has been also tested with benchmark examples, and works well. But for alcove_uncicycle_sphere doesn't return a solution within the timelimit used for icra submission. I will address this hidden bug in March.

**Comment by quimortiz** [comment]
thanks! can you add 1) test of tdbastar with constraints? 2) test of your reverse search?

**Comment by akmaralAW** [comment]
for the test of reverse search I did visualization with heatmap, would it be good for you ?

**Comment by quimortiz** [comment]
no, visualization is not enough. Because when we run the test we are not going to visualize. Can you add one small test that does first reverse search, then check that the heuristic value at the original start is a given value (with some tolerance), and then does forward search and checks that you find a solution? It is ok if the test is only for one system.

**Comment by quimortiz** [comment]
for constraints, can you check that the found solution does not violate the constraints?

**Comment by akmaralAW** [comment]
For the reverse search: what you mean is first reverse search, get heuristics, then forward search using obtained heuristics, but I did not get "checks that you find a solution" - usual forward run and final solution of it ?

**Comment by akmaralAW** [comment]
Reverse search for a single robot - unicycle1_v0 is added, and it supports the forward search as well using the heuristic.

**Comment by quimortiz** [comment]
i guess i wont have #define BASE_PATH_MOTIONS "../../new_format_motions/" in my computer? the minimum amount of required motions to pass the test should be publicly and easily available. One option is to put them in dynomotions. 
what do you want to do? Or online somewhere, and download them if not available at runtime.

**Comment by akmaralAW** [comment]
they are already online in tubcloud and publicly available. I will check how to download it while running the code. This is easier I think instead of extracting motion primitives again and putting them into dynomotions.

**Comment by quimortiz** [comment]
done!

**Pull request merged**
